# Generated by Django 2.2 on 2022-01-17 04:53

import django.core.validators
from django.db import migrations, models
import stream_bunny_v0_2_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=12, null=True)),
                ('imdb_rating', models.CharField(blank=True, max_length=3, null=True)),
                ('poster_link', models.CharField(blank=True, max_length=280, null=True)),
                ('poster_low', models.CharField(blank=True, max_length=280, null=True)),
                ('plot', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('year', models.PositiveSmallIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1878), stream_bunny_v0_2_app.models.max_value_current_year])),
                ('director', models.CharField(max_length=100, null=True)),
                ('genres', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
