# Generated by Django 2.2 on 2022-01-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('stream_bunny_v0_2_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_by', to='login_app.User'),
        ),
    ]
